FROM ubuntu:bionic

RUN apt-get update

LABEL maintainer=superuser \
    org.opencontainers.image.authors=superuser \
    org.opencontainers.image.title="${IMAGE_NAME}"\
    org.opencontainers.image.description="Demo for Sommercampus 2018" \
    org.opencontainers.image.version="${GO_PIPELINE_COUNTER}" \
    org.opencontainers.image.source="${GO_SERVER_URL}" \
    org.opencontainers.image.revision="${GO_REVISION_MYGIT}"